'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class cat
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AM3D.cat", GetType(cat).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Refresca llista.
        '''</summary>
        Friend Shared ReadOnly Property BResfrescar() As String
            Get
                Return ResourceManager.GetString("BResfrescar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Actualitzar.
        '''</summary>
        Friend Shared ReadOnly Property BTActualitzar() As String
            Get
                Return ResourceManager.GetString("BTActualitzar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Afegir.
        '''</summary>
        Friend Shared ReadOnly Property BTAfegir() As String
            Get
                Return ResourceManager.GetString("BTAfegir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Borrar.
        '''</summary>
        Friend Shared ReadOnly Property BTBorrar() As String
            Get
                Return ResourceManager.GetString("BTBorrar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Canviar Bobina.
        '''</summary>
        Friend Shared ReadOnly Property BTCambiarBobina() As String
            Get
                Return ResourceManager.GetString("BTCambiarBobina", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel·lar.
        '''</summary>
        Friend Shared ReadOnly Property BTCancelar() As String
            Get
                Return ResourceManager.GetString("BTCancelar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Canviar.
        '''</summary>
        Friend Shared ReadOnly Property BTCanviar() As String
            Get
                Return ResourceManager.GetString("BTCanviar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connectar.
        '''</summary>
        Friend Shared ReadOnly Property BTConnectar() As String
            Get
                Return ResourceManager.GetString("BTConnectar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Crear.
        '''</summary>
        Friend Shared ReadOnly Property BTCrear() As String
            Get
                Return ResourceManager.GetString("BTCrear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eliminar Bobina.
        '''</summary>
        Friend Shared ReadOnly Property BTEliminarBobina() As String
            Get
                Return ResourceManager.GetString("BTEliminarBobina", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eliminar Color.
        '''</summary>
        Friend Shared ReadOnly Property BTEliminarColor() As String
            Get
                Return ResourceManager.GetString("BTEliminarColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eliminar GCode.
        '''</summary>
        Friend Shared ReadOnly Property BTEliminarGcode() As String
            Get
                Return ResourceManager.GetString("BTEliminarGcode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eliminar Impressora.
        '''</summary>
        Friend Shared ReadOnly Property BTEliminarImpressora() As String
            Get
                Return ResourceManager.GetString("BTEliminarImpressora", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eliminar Marca.
        '''</summary>
        Friend Shared ReadOnly Property BTEliminarMarca() As String
            Get
                Return ResourceManager.GetString("BTEliminarMarca", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eliminar Material.
        '''</summary>
        Friend Shared ReadOnly Property BTEliminarMaterial() As String
            Get
                Return ResourceManager.GetString("BTEliminarMaterial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eliminar Model.
        '''</summary>
        Friend Shared ReadOnly Property BTEliminarModel() As String
            Get
                Return ResourceManager.GetString("BTEliminarModel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eliminar Usuari.
        '''</summary>
        Friend Shared ReadOnly Property BTEliminarUsuari() As String
            Get
                Return ResourceManager.GetString("BTEliminarUsuari", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Guardar.
        '''</summary>
        Friend Shared ReadOnly Property BTGuardar() As String
            Get
                Return ResourceManager.GetString("BTGuardar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pausar.
        '''</summary>
        Friend Shared ReadOnly Property BTImpressionsPausar() As String
            Get
                Return ResourceManager.GetString("BTImpressionsPausar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Retirar peça.
        '''</summary>
        Friend Shared ReadOnly Property BTImpressionsPeçaRetirada() As String
            Get
                Return ResourceManager.GetString("BTImpressionsPeçaRetirada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imprimir.
        '''</summary>
        Friend Shared ReadOnly Property BTImprimir() As String
            Get
                Return ResourceManager.GetString("BTImprimir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imprimir Gcode.
        '''</summary>
        Friend Shared ReadOnly Property BTImprimirG() As String
            Get
                Return ResourceManager.GetString("BTImprimirG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Llista.
        '''</summary>
        Friend Shared ReadOnly Property BTLlista() As String
            Get
                Return ResourceManager.GetString("BTLlista", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modificar Bobina.
        '''</summary>
        Friend Shared ReadOnly Property BTModificarBobina() As String
            Get
                Return ResourceManager.GetString("BTModificarBobina", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modificar Color.
        '''</summary>
        Friend Shared ReadOnly Property BTModificarColor() As String
            Get
                Return ResourceManager.GetString("BTModificarColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Llista.
        '''</summary>
        Friend Shared ReadOnly Property BTModificarEliminar() As String
            Get
                Return ResourceManager.GetString("BTModificarEliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modificar GCode.
        '''</summary>
        Friend Shared ReadOnly Property BTModificarGcode() As String
            Get
                Return ResourceManager.GetString("BTModificarGcode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modificar Impressora.
        '''</summary>
        Friend Shared ReadOnly Property BTModificarImpressora() As String
            Get
                Return ResourceManager.GetString("BTModificarImpressora", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modificar Marca.
        '''</summary>
        Friend Shared ReadOnly Property BTModificarMarca() As String
            Get
                Return ResourceManager.GetString("BTModificarMarca", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modificar Material.
        '''</summary>
        Friend Shared ReadOnly Property BTModificarMaterial() As String
            Get
                Return ResourceManager.GetString("BTModificarMaterial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modificar Model.
        '''</summary>
        Friend Shared ReadOnly Property BTModificarModel() As String
            Get
                Return ResourceManager.GetString("BTModificarModel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modificar Usuari.
        '''</summary>
        Friend Shared ReadOnly Property BTModificarUsuari() As String
            Get
                Return ResourceManager.GetString("BTModificarUsuari", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Entrar.
        '''</summary>
        Friend Shared ReadOnly Property ButtonLogin() As String
            Get
                Return ResourceManager.GetString("ButtonLogin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Carregant.
        '''</summary>
        Friend Shared ReadOnly Property ButtonLogin_Cargando() As String
            Get
                Return ResourceManager.GetString("ButtonLogin_Cargando", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Canviar contrasenya.
        '''</summary>
        Friend Shared ReadOnly Property CanviarContrasenya() As String
            Get
                Return ResourceManager.GetString("CanviarContrasenya", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modificar.
        '''</summary>
        Friend Shared ReadOnly Property CBModificar() As String
            Get
                Return ResourceManager.GetString("CBModificar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recordar usuari.
        '''</summary>
        Friend Shared ReadOnly Property CBRecordar() As String
            Get
                Return ResourceManager.GetString("CBRecordar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No s&apos;ha pogut crear el fitxer.
        '''</summary>
        Friend Shared ReadOnly Property ErrorFitxer() As String
            Get
                Return ResourceManager.GetString("ErrorFitxer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generar Estadistiques.
        '''</summary>
        Friend Shared ReadOnly Property GenerarEstad() As String
            Get
                Return ResourceManager.GetString("GenerarEstad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: L&apos;usuari o contrasenya és incorrecte..
        '''</summary>
        Friend Shared ReadOnly Property LabelErrorLogin() As String
            Get
                Return ResourceManager.GetString("LabelErrorLogin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Impressora guardada correctament..
        '''</summary>
        Friend Shared ReadOnly Property LabelnfoCorrecte() As String
            Get
                Return ResourceManager.GetString("LabelnfoCorrecte", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error en guardar la impressora..
        '''</summary>
        Friend Shared ReadOnly Property LabelnfoError() As String
            Get
                Return ResourceManager.GetString("LabelnfoError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ompliu tots els camps..
        '''</summary>
        Friend Shared ReadOnly Property LabelnfoNoSelect() As String
            Get
                Return ResourceManager.GetString("LabelnfoNoSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contrasenya actual.
        '''</summary>
        Friend Shared ReadOnly Property LActual() As String
            Get
                Return ResourceManager.GetString("LActual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aplicacions funcionals.
        '''</summary>
        Friend Shared ReadOnly Property LApliFun() As String
            Get
                Return ResourceManager.GetString("LApliFun", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Area d&apos;impressió X.
        '''</summary>
        Friend Shared ReadOnly Property LAreaX() As String
            Get
                Return ResourceManager.GetString("LAreaX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Area d&apos;impressió Y.
        '''</summary>
        Friend Shared ReadOnly Property LAreaY() As String
            Get
                Return ResourceManager.GetString("LAreaY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Area d&apos;impressió Z.
        '''</summary>
        Friend Shared ReadOnly Property LAreaZ() As String
            Get
                Return ResourceManager.GetString("LAreaZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Control.
        '''</summary>
        Friend Shared ReadOnly Property LBControl() As String
            Get
                Return ResourceManager.GetString("LBControl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Benvingut.
        '''</summary>
        Friend Shared ReadOnly Property LBenvingut() As String
            Get
                Return ResourceManager.GetString("LBenvingut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gestió.
        '''</summary>
        Friend Shared ReadOnly Property LBGestio() As String
            Get
                Return ResourceManager.GetString("LBGestio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Impressions.
        '''</summary>
        Friend Shared ReadOnly Property LBImpressions() As String
            Get
                Return ResourceManager.GetString("LBImpressions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Impressores.
        '''</summary>
        Friend Shared ReadOnly Property LBImpressores() As String
            Get
                Return ResourceManager.GetString("LBImpressores", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bobina.
        '''</summary>
        Friend Shared ReadOnly Property LBobina() As String
            Get
                Return ResourceManager.GetString("LBobina", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bobines.
        '''</summary>
        Friend Shared ReadOnly Property LBobines() As String
            Get
                Return ResourceManager.GetString("LBobines", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Canviar contrasenya..
        '''</summary>
        Friend Shared ReadOnly Property LCanvContr() As String
            Get
                Return ResourceManager.GetString("LCanvContr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cognom.
        '''</summary>
        Friend Shared ReadOnly Property LCognom() As String
            Get
                Return ResourceManager.GetString("LCognom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Color.
        '''</summary>
        Friend Shared ReadOnly Property LColor() As String
            Get
                Return ResourceManager.GetString("LColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contrasenya.
        '''</summary>
        Friend Shared ReadOnly Property LContrasenya() As String
            Get
                Return ResourceManager.GetString("LContrasenya", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Control.
        '''</summary>
        Friend Shared ReadOnly Property LControl() As String
            Get
                Return ResourceManager.GetString("LControl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to E-mail.
        '''</summary>
        Friend Shared ReadOnly Property LCorreu() As String
            Get
                Return ResourceManager.GetString("LCorreu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dades d&apos;usuari..
        '''</summary>
        Friend Shared ReadOnly Property LDades() As String
            Get
                Return ResourceManager.GetString("LDades", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Diàmetre.
        '''</summary>
        Friend Shared ReadOnly Property LDiametre() As String
            Get
                Return ResourceManager.GetString("LDiametre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Diàmetre de filament.
        '''</summary>
        Friend Shared ReadOnly Property LDiametreFil() As String
            Get
                Return ResourceManager.GetString("LDiametreFil", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DNI.
        '''</summary>
        Friend Shared ReadOnly Property LDni() As String
            Get
                Return ResourceManager.GetString("LDni", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to E-mail.
        '''</summary>
        Friend Shared ReadOnly Property LEmail() As String
            Get
                Return ResourceManager.GetString("LEmail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gcode.
        '''</summary>
        Friend Shared ReadOnly Property LGcode() As String
            Get
                Return ResourceManager.GetString("LGcode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gestió.
        '''</summary>
        Friend Shared ReadOnly Property LGestio() As String
            Get
                Return ResourceManager.GetString("LGestio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Codi HEX.
        '''</summary>
        Friend Shared ReadOnly Property LHex() As String
            Get
                Return ResourceManager.GetString("LHex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Idioma.
        '''</summary>
        Friend Shared ReadOnly Property Lidioma() As String
            Get
                Return ResourceManager.GetString("Lidioma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Impressora.
        '''</summary>
        Friend Shared ReadOnly Property LImpressora() As String
            Get
                Return ResourceManager.GetString("LImpressora", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Impressores.
        '''</summary>
        Friend Shared ReadOnly Property LImpressores() As String
            Get
                Return ResourceManager.GetString("LImpressores", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inici.
        '''</summary>
        Friend Shared ReadOnly Property LInici() As String
            Get
                Return ResourceManager.GetString("LInici", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Marca.
        '''</summary>
        Friend Shared ReadOnly Property LMarca() As String
            Get
                Return ResourceManager.GetString("LMarca", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Marca productora.
        '''</summary>
        Friend Shared ReadOnly Property LMarcaProductora() As String
            Get
                Return ResourceManager.GetString("LMarcaProductora", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Material.
        '''</summary>
        Friend Shared ReadOnly Property LMaterial() As String
            Get
                Return ResourceManager.GetString("LMaterial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Material suportat.
        '''</summary>
        Friend Shared ReadOnly Property LMaterialsSup() As String
            Get
                Return ResourceManager.GetString("LMaterialsSup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Material Suportat.
        '''</summary>
        Friend Shared ReadOnly Property LMaterialSup() As String
            Get
                Return ResourceManager.GetString("LMaterialSup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Model.
        '''</summary>
        Friend Shared ReadOnly Property LModel() As String
            Get
                Return ResourceManager.GetString("LModel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Models.
        '''</summary>
        Friend Shared ReadOnly Property LModels() As String
            Get
                Return ResourceManager.GetString("LModels", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nº Copies.
        '''</summary>
        Friend Shared ReadOnly Property LNCopies() As String
            Get
                Return ResourceManager.GetString("LNCopies", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nº Extrusors.
        '''</summary>
        Friend Shared ReadOnly Property LNExtru() As String
            Get
                Return ResourceManager.GetString("LNExtru", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nom.
        '''</summary>
        Friend Shared ReadOnly Property LNom() As String
            Get
                Return ResourceManager.GetString("LNom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nom del GCode.
        '''</summary>
        Friend Shared ReadOnly Property LNomGcode() As String
            Get
                Return ResourceManager.GetString("LNomGcode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nom d&apos;usuari.
        '''</summary>
        Friend Shared ReadOnly Property LNomUsuari() As String
            Get
                Return ResourceManager.GetString("LNomUsuari", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nova contrasenya.
        '''</summary>
        Friend Shared ReadOnly Property LNova() As String
            Get
                Return ResourceManager.GetString("LNova", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sortir.
        '''</summary>
        Friend Shared ReadOnly Property Logout() As String
            Get
                Return ResourceManager.GetString("Logout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Permisos.
        '''</summary>
        Friend Shared ReadOnly Property LPermisos() As String
            Get
                Return ResourceManager.GetString("LPermisos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Repeteix la contrasenya.
        '''</summary>
        Friend Shared ReadOnly Property LRContra() As String
            Get
                Return ResourceManager.GetString("LRContra", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Repeteix la contrasenya.
        '''</summary>
        Friend Shared ReadOnly Property LRepContrasenya() As String
            Get
                Return ResourceManager.GetString("LRepContrasenya", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resolució máxima de capa.
        '''</summary>
        Friend Shared ReadOnly Property LResMaxCapa() As String
            Get
                Return ResourceManager.GetString("LResMaxCapa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resolució mínima de capa.
        '''</summary>
        Friend Shared ReadOnly Property LResMinCapa() As String
            Get
                Return ResourceManager.GetString("LResMinCapa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ruta del fitxer.
        '''</summary>
        Friend Shared ReadOnly Property LRutaFich() As String
            Get
                Return ResourceManager.GetString("LRutaFich", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seleciona un idioma..
        '''</summary>
        Friend Shared ReadOnly Property LSelecionarIdioma() As String
            Get
                Return ResourceManager.GetString("LSelecionarIdioma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nom Tècnic.
        '''</summary>
        Friend Shared ReadOnly Property LTecnic() As String
            Get
                Return ResourceManager.GetString("LTecnic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Temperatura máxima del extrusor.
        '''</summary>
        Friend Shared ReadOnly Property LTempMaxExt() As String
            Get
                Return ResourceManager.GetString("LTempMaxExt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Temperatura máxima del llit.
        '''</summary>
        Friend Shared ReadOnly Property LTempMaxLlit() As String
            Get
                Return ResourceManager.GetString("LTempMaxLlit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Temperatura mínima del extrusor.
        '''</summary>
        Friend Shared ReadOnly Property LTempMinExt() As String
            Get
                Return ResourceManager.GetString("LTempMinExt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Temperatura mínima del llit.
        '''</summary>
        Friend Shared ReadOnly Property LTempMinLlit() As String
            Get
                Return ResourceManager.GetString("LTempMinLlit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Usuari.
        '''</summary>
        Friend Shared ReadOnly Property LUsuari() As String
            Get
                Return ResourceManager.GetString("LUsuari", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Usuaris.
        '''</summary>
        Friend Shared ReadOnly Property LUsuaris() As String
            Get
                Return ResourceManager.GetString("LUsuaris", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Velocitat máxima de l&apos;extrusor.
        '''</summary>
        Friend Shared ReadOnly Property LVelMaxExt() As String
            Get
                Return ResourceManager.GetString("LVelMaxExt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fitxers generats correctament..
        '''</summary>
        Friend Shared ReadOnly Property MFicheroCorrectos() As String
            Get
                Return ResourceManager.GetString("MFicheroCorrectos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error al generar els fitxers..
        '''</summary>
        Friend Shared ReadOnly Property MFicheroError() As String
            Get
                Return ResourceManager.GetString("MFicheroError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eliminació feta correctament..
        '''</summary>
        Friend Shared ReadOnly Property MSGDeleteCorrect() As String
            Get
                Return ResourceManager.GetString("MSGDeleteCorrect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error en l&apos;eliminació..
        '''</summary>
        Friend Shared ReadOnly Property MSGDeleteError() As String
            Get
                Return ResourceManager.GetString("MSGDeleteError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Impressora cancel·lada correctament..
        '''</summary>
        Friend Shared ReadOnly Property MSGImpressionsCancelarCorrect() As String
            Get
                Return ResourceManager.GetString("MSGImpressionsCancelarCorrect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No s&apos;ha pogut cancel·lar la impressora..
        '''</summary>
        Friend Shared ReadOnly Property MSGImpressionsCancelarError() As String
            Get
                Return ResourceManager.GetString("MSGImpressionsCancelarError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aquesta Impressora no es pot cancel·lar..
        '''</summary>
        Friend Shared ReadOnly Property MSGImpressionsCancelarErrorSelect() As String
            Get
                Return ResourceManager.GetString("MSGImpressionsCancelarErrorSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Estat actualitzat correctament..
        '''</summary>
        Friend Shared ReadOnly Property MSGImpressionsRetirarCorrect() As String
            Get
                Return ResourceManager.GetString("MSGImpressionsRetirarCorrect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No s&apos;ha pogut actualitzar l&apos;estat..
        '''</summary>
        Friend Shared ReadOnly Property MSGImpressionsRetirarError() As String
            Get
                Return ResourceManager.GetString("MSGImpressionsRetirarError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No es pot retirar una impressió no finalitzada..
        '''</summary>
        Friend Shared ReadOnly Property MSGImpressionsRetirarErrorSelect() As String
            Get
                Return ResourceManager.GetString("MSGImpressionsRetirarErrorSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La inserció ha estat correcta..
        '''</summary>
        Friend Shared ReadOnly Property MSGInsertCorrecto() As String
            Get
                Return ResourceManager.GetString("MSGInsertCorrecto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error en la inserció..
        '''</summary>
        Friend Shared ReadOnly Property MSGInsertIncorrecto() As String
            Get
                Return ResourceManager.GetString("MSGInsertIncorrecto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Omple tots els camps..
        '''</summary>
        Friend Shared ReadOnly Property MSGRellenarError() As String
            Get
                Return ResourceManager.GetString("MSGRellenarError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La contrasenya actual no és correcta..
        '''</summary>
        Friend Shared ReadOnly Property MSGUserContrasenyaError() As String
            Get
                Return ResourceManager.GetString("MSGUserContrasenyaError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to L&apos;nickname és usat..
        '''</summary>
        Friend Shared ReadOnly Property MSGUserExist() As String
            Get
                Return ResourceManager.GetString("MSGUserExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contrasenya actualitzada correctament..
        '''</summary>
        Friend Shared ReadOnly Property MSGUserPasswordUpdateCorrect() As String
            Get
                Return ResourceManager.GetString("MSGUserPasswordUpdateCorrect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error en desar la contrasenya de l&apos;usuari..
        '''</summary>
        Friend Shared ReadOnly Property MSGUserPasswordUpdateError() As String
            Get
                Return ResourceManager.GetString("MSGUserPasswordUpdateError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Les contrasenyes no coincideixen..
        '''</summary>
        Friend Shared ReadOnly Property MSGUserRepetirError() As String
            Get
                Return ResourceManager.GetString("MSGUserRepetirError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dades d&apos;usuari guardats correctament..
        '''</summary>
        Friend Shared ReadOnly Property MSGUserUpdateCorrect() As String
            Get
                Return ResourceManager.GetString("MSGUserUpdateCorrect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error en desar dades d&apos;usuari..
        '''</summary>
        Friend Shared ReadOnly Property MSGUserUpdateError() As String
            Get
                Return ResourceManager.GetString("MSGUserUpdateError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Canviar idioma.
        '''</summary>
        Friend Shared ReadOnly Property opcioCambiarIdioma() As String
            Get
                Return ResourceManager.GetString("opcioCambiarIdioma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generar estadístiques.
        '''</summary>
        Friend Shared ReadOnly Property opcioGenerarEstadistiques() As String
            Get
                Return ResourceManager.GetString("opcioGenerarEstadistiques", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Perfil.
        '''</summary>
        Friend Shared ReadOnly Property opcioPerfil() As String
            Get
                Return ResourceManager.GetString("opcioPerfil", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tancar la sessió.
        '''</summary>
        Friend Shared ReadOnly Property opcioSortir() As String
            Get
                Return ResourceManager.GetString("opcioSortir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Perfil.
        '''</summary>
        Friend Shared ReadOnly Property Perfil() As String
            Get
                Return ResourceManager.GetString("Perfil", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
