'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class eng
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AM3D.eng", GetType(eng).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ad.
        '''</summary>
        Friend Shared ReadOnly Property BTAfegir() As String
            Get
                Return ResourceManager.GetString("BTAfegir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cancel.
        '''</summary>
        Friend Shared ReadOnly Property BTCancelar() As String
            Get
                Return ResourceManager.GetString("BTCancelar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Change.
        '''</summary>
        Friend Shared ReadOnly Property BTCanviar() As String
            Get
                Return ResourceManager.GetString("BTCanviar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Change Coil.
        '''</summary>
        Friend Shared ReadOnly Property BTCanviarBobina() As String
            Get
                Return ResourceManager.GetString("BTCanviarBobina", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Connect.
        '''</summary>
        Friend Shared ReadOnly Property BTConnectar() As String
            Get
                Return ResourceManager.GetString("BTConnectar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Remove Coil.
        '''</summary>
        Friend Shared ReadOnly Property BTEliminarBobina() As String
            Get
                Return ResourceManager.GetString("BTEliminarBobina", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Remove Color.
        '''</summary>
        Friend Shared ReadOnly Property BTEliminarColor() As String
            Get
                Return ResourceManager.GetString("BTEliminarColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Remove GCode.
        '''</summary>
        Friend Shared ReadOnly Property BTEliminarGcode() As String
            Get
                Return ResourceManager.GetString("BTEliminarGcode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Remove Printer.
        '''</summary>
        Friend Shared ReadOnly Property BTEliminarImpressora() As String
            Get
                Return ResourceManager.GetString("BTEliminarImpressora", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Remove Brand.
        '''</summary>
        Friend Shared ReadOnly Property BTEliminarMarca() As String
            Get
                Return ResourceManager.GetString("BTEliminarMarca", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Remove Material.
        '''</summary>
        Friend Shared ReadOnly Property BTEliminarMaterial() As String
            Get
                Return ResourceManager.GetString("BTEliminarMaterial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Remove Model.
        '''</summary>
        Friend Shared ReadOnly Property BTEliminarModel() As String
            Get
                Return ResourceManager.GetString("BTEliminarModel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Remove User.
        '''</summary>
        Friend Shared ReadOnly Property BTEliminarUsuari() As String
            Get
                Return ResourceManager.GetString("BTEliminarUsuari", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pause.
        '''</summary>
        Friend Shared ReadOnly Property BTImpressionsPausar() As String
            Get
                Return ResourceManager.GetString("BTImpressionsPausar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Remove Piece.
        '''</summary>
        Friend Shared ReadOnly Property BTImpressionsPeçaRetirada() As String
            Get
                Return ResourceManager.GetString("BTImpressionsPeçaRetirada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Print.
        '''</summary>
        Friend Shared ReadOnly Property BTImprimir() As String
            Get
                Return ResourceManager.GetString("BTImprimir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Print GCode.
        '''</summary>
        Friend Shared ReadOnly Property BTImprimirG() As String
            Get
                Return ResourceManager.GetString("BTImprimirG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a List.
        '''</summary>
        Friend Shared ReadOnly Property BTLlista() As String
            Get
                Return ResourceManager.GetString("BTLlista", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Change Coil.
        '''</summary>
        Friend Shared ReadOnly Property BTModificarBobina() As String
            Get
                Return ResourceManager.GetString("BTModificarBobina", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Change Color.
        '''</summary>
        Friend Shared ReadOnly Property BTModificarColor() As String
            Get
                Return ResourceManager.GetString("BTModificarColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Change/Remove.
        '''</summary>
        Friend Shared ReadOnly Property BTModificarEliminar() As String
            Get
                Return ResourceManager.GetString("BTModificarEliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Change GCode.
        '''</summary>
        Friend Shared ReadOnly Property BTModificarGcode() As String
            Get
                Return ResourceManager.GetString("BTModificarGcode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Change Printer.
        '''</summary>
        Friend Shared ReadOnly Property BTModificarImpressora() As String
            Get
                Return ResourceManager.GetString("BTModificarImpressora", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Change Brand.
        '''</summary>
        Friend Shared ReadOnly Property BTModificarMarca() As String
            Get
                Return ResourceManager.GetString("BTModificarMarca", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Change Material.
        '''</summary>
        Friend Shared ReadOnly Property BTModificarMaterial() As String
            Get
                Return ResourceManager.GetString("BTModificarMaterial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Chanhe Model.
        '''</summary>
        Friend Shared ReadOnly Property BTModificarModel() As String
            Get
                Return ResourceManager.GetString("BTModificarModel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Change User.
        '''</summary>
        Friend Shared ReadOnly Property BTModificarUsuari() As String
            Get
                Return ResourceManager.GetString("BTModificarUsuari", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Login.
        '''</summary>
        Friend Shared ReadOnly Property ButtonLogin() As String
            Get
                Return ResourceManager.GetString("ButtonLogin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Change Password.
        '''</summary>
        Friend Shared ReadOnly Property CanviarContrasenya() As String
            Get
                Return ResourceManager.GetString("CanviarContrasenya", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Change.
        '''</summary>
        Friend Shared ReadOnly Property CBModificar() As String
            Get
                Return ResourceManager.GetString("CBModificar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Remember User.
        '''</summary>
        Friend Shared ReadOnly Property CBRecordar() As String
            Get
                Return ResourceManager.GetString("CBRecordar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The file could not be created.
        '''</summary>
        Friend Shared ReadOnly Property ErrorFitxer() As String
            Get
                Return ResourceManager.GetString("ErrorFitxer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Generate Statistics.
        '''</summary>
        Friend Shared ReadOnly Property GenerarEstad() As String
            Get
                Return ResourceManager.GetString("GenerarEstad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Actual.
        '''</summary>
        Friend Shared ReadOnly Property LActual() As String
            Get
                Return ResourceManager.GetString("LActual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Functional applications.
        '''</summary>
        Friend Shared ReadOnly Property LApliFun() As String
            Get
                Return ResourceManager.GetString("LApliFun", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a X printing area.
        '''</summary>
        Friend Shared ReadOnly Property LAreaX() As String
            Get
                Return ResourceManager.GetString("LAreaX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Y printing area.
        '''</summary>
        Friend Shared ReadOnly Property LAreaY() As String
            Get
                Return ResourceManager.GetString("LAreaY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Z printing area.
        '''</summary>
        Friend Shared ReadOnly Property LAreaZ() As String
            Get
                Return ResourceManager.GetString("LAreaZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Control.
        '''</summary>
        Friend Shared ReadOnly Property LBControl() As String
            Get
                Return ResourceManager.GetString("LBControl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Welcome.
        '''</summary>
        Friend Shared ReadOnly Property LBenvingut() As String
            Get
                Return ResourceManager.GetString("LBenvingut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Management.
        '''</summary>
        Friend Shared ReadOnly Property LBGestio() As String
            Get
                Return ResourceManager.GetString("LBGestio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Printings.
        '''</summary>
        Friend Shared ReadOnly Property LBImpressions() As String
            Get
                Return ResourceManager.GetString("LBImpressions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Printers.
        '''</summary>
        Friend Shared ReadOnly Property LBImpressores() As String
            Get
                Return ResourceManager.GetString("LBImpressores", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Coil.
        '''</summary>
        Friend Shared ReadOnly Property LBobina() As String
            Get
                Return ResourceManager.GetString("LBobina", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Coils.
        '''</summary>
        Friend Shared ReadOnly Property LBobines() As String
            Get
                Return ResourceManager.GetString("LBobines", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Change Password.
        '''</summary>
        Friend Shared ReadOnly Property LCanvContr() As String
            Get
                Return ResourceManager.GetString("LCanvContr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Surname.
        '''</summary>
        Friend Shared ReadOnly Property LCognom() As String
            Get
                Return ResourceManager.GetString("LCognom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Color.
        '''</summary>
        Friend Shared ReadOnly Property LColor() As String
            Get
                Return ResourceManager.GetString("LColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Password.
        '''</summary>
        Friend Shared ReadOnly Property LContrasenya() As String
            Get
                Return ResourceManager.GetString("LContrasenya", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Control.
        '''</summary>
        Friend Shared ReadOnly Property LControl() As String
            Get
                Return ResourceManager.GetString("LControl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Email.
        '''</summary>
        Friend Shared ReadOnly Property LCorreu() As String
            Get
                Return ResourceManager.GetString("LCorreu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Details.
        '''</summary>
        Friend Shared ReadOnly Property LDades() As String
            Get
                Return ResourceManager.GetString("LDades", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Diameter.
        '''</summary>
        Friend Shared ReadOnly Property LDiametre() As String
            Get
                Return ResourceManager.GetString("LDiametre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Filament diameter.
        '''</summary>
        Friend Shared ReadOnly Property LDiametreFil() As String
            Get
                Return ResourceManager.GetString("LDiametreFil", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Dni.
        '''</summary>
        Friend Shared ReadOnly Property LDni() As String
            Get
                Return ResourceManager.GetString("LDni", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Email.
        '''</summary>
        Friend Shared ReadOnly Property LEmail() As String
            Get
                Return ResourceManager.GetString("LEmail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Gcode.
        '''</summary>
        Friend Shared ReadOnly Property LGcode() As String
            Get
                Return ResourceManager.GetString("LGcode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Management.
        '''</summary>
        Friend Shared ReadOnly Property LGestio() As String
            Get
                Return ResourceManager.GetString("LGestio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a HEX Code.
        '''</summary>
        Friend Shared ReadOnly Property LHex() As String
            Get
                Return ResourceManager.GetString("LHex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Language.
        '''</summary>
        Friend Shared ReadOnly Property Lidioma() As String
            Get
                Return ResourceManager.GetString("Lidioma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Printer.
        '''</summary>
        Friend Shared ReadOnly Property LImpressora() As String
            Get
                Return ResourceManager.GetString("LImpressora", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Printing.
        '''</summary>
        Friend Shared ReadOnly Property LImpressores() As String
            Get
                Return ResourceManager.GetString("LImpressores", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Home.
        '''</summary>
        Friend Shared ReadOnly Property LInici() As String
            Get
                Return ResourceManager.GetString("LInici", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Brand.
        '''</summary>
        Friend Shared ReadOnly Property LMarca() As String
            Get
                Return ResourceManager.GetString("LMarca", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Producer brand.
        '''</summary>
        Friend Shared ReadOnly Property LMarcaProductora() As String
            Get
                Return ResourceManager.GetString("LMarcaProductora", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Material.
        '''</summary>
        Friend Shared ReadOnly Property LMaterial() As String
            Get
                Return ResourceManager.GetString("LMaterial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Supported material.
        '''</summary>
        Friend Shared ReadOnly Property LMaterialsSup() As String
            Get
                Return ResourceManager.GetString("LMaterialsSup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Model.
        '''</summary>
        Friend Shared ReadOnly Property LModel() As String
            Get
                Return ResourceManager.GetString("LModel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Models.
        '''</summary>
        Friend Shared ReadOnly Property LModels() As String
            Get
                Return ResourceManager.GetString("LModels", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nº Copies.
        '''</summary>
        Friend Shared ReadOnly Property LNCopies() As String
            Get
                Return ResourceManager.GetString("LNCopies", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nº Extruders.
        '''</summary>
        Friend Shared ReadOnly Property LNExtru() As String
            Get
                Return ResourceManager.GetString("LNExtru", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Name.
        '''</summary>
        Friend Shared ReadOnly Property LNom() As String
            Get
                Return ResourceManager.GetString("LNom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Name of the GCode.
        '''</summary>
        Friend Shared ReadOnly Property LNomGcode() As String
            Get
                Return ResourceManager.GetString("LNomGcode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a User name.
        '''</summary>
        Friend Shared ReadOnly Property LNomUsuari() As String
            Get
                Return ResourceManager.GetString("LNomUsuari", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a New.
        '''</summary>
        Friend Shared ReadOnly Property LNova() As String
            Get
                Return ResourceManager.GetString("LNova", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Logout.
        '''</summary>
        Friend Shared ReadOnly Property Logout() As String
            Get
                Return ResourceManager.GetString("Logout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Repeat the password.
        '''</summary>
        Friend Shared ReadOnly Property LRContra() As String
            Get
                Return ResourceManager.GetString("LRContra", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Maximum layer resolution.
        '''</summary>
        Friend Shared ReadOnly Property LResMaxCapa() As String
            Get
                Return ResourceManager.GetString("LResMaxCapa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Minimum layer resolution.
        '''</summary>
        Friend Shared ReadOnly Property LResMinCapa() As String
            Get
                Return ResourceManager.GetString("LResMinCapa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a File path.
        '''</summary>
        Friend Shared ReadOnly Property LRutaFich() As String
            Get
                Return ResourceManager.GetString("LRutaFich", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Select a language.
        '''</summary>
        Friend Shared ReadOnly Property LSelecionarIdioma() As String
            Get
                Return ResourceManager.GetString("LSelecionarIdioma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Technical Name.
        '''</summary>
        Friend Shared ReadOnly Property LTecnic() As String
            Get
                Return ResourceManager.GetString("LTecnic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Maximum extruder temperature.
        '''</summary>
        Friend Shared ReadOnly Property LTempMaxExt() As String
            Get
                Return ResourceManager.GetString("LTempMaxExt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Maximum bed temperature.
        '''</summary>
        Friend Shared ReadOnly Property LTempMaxLlit() As String
            Get
                Return ResourceManager.GetString("LTempMaxLlit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Minimum extruder temperature.
        '''</summary>
        Friend Shared ReadOnly Property LTempMinExt() As String
            Get
                Return ResourceManager.GetString("LTempMinExt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Minimum bed temperature.
        '''</summary>
        Friend Shared ReadOnly Property LTempMinLlit() As String
            Get
                Return ResourceManager.GetString("LTempMinLlit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a User.
        '''</summary>
        Friend Shared ReadOnly Property LUsuari() As String
            Get
                Return ResourceManager.GetString("LUsuari", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Users.
        '''</summary>
        Friend Shared ReadOnly Property LUsuaris() As String
            Get
                Return ResourceManager.GetString("LUsuaris", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Maximum speed of the extruder.
        '''</summary>
        Friend Shared ReadOnly Property LVelMaxExt() As String
            Get
                Return ResourceManager.GetString("LVelMaxExt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Change language.
        '''</summary>
        Friend Shared ReadOnly Property opcioCambiarIdioma() As String
            Get
                Return ResourceManager.GetString("opcioCambiarIdioma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Generate Statistics.
        '''</summary>
        Friend Shared ReadOnly Property opcioGenerarEstadistiques() As String
            Get
                Return ResourceManager.GetString("opcioGenerarEstadistiques", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Profile.
        '''</summary>
        Friend Shared ReadOnly Property opcioPerfil() As String
            Get
                Return ResourceManager.GetString("opcioPerfil", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Logout.
        '''</summary>
        Friend Shared ReadOnly Property opcioSortir() As String
            Get
                Return ResourceManager.GetString("opcioSortir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Profile.
        '''</summary>
        Friend Shared ReadOnly Property Perfil() As String
            Get
                Return ResourceManager.GetString("Perfil", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
